name: Build

on:
    - push
    - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install ubuntu packages to lint
      run: sudo apt install clang-format-10 flake8
    - name: Check C lint
      run: bin/check-clang-format
    - name: Check python lint
      run: flake8

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install ubuntu packages to build
      run: sudo apt install cmake ninja-build
    - name: build
      run: |
          cmake -G Ninja ports/linux/
          ninja
    - name: MNIST
      run: |
          ninja mnist
    - name: ONNX Test Cases
      run: |
          ninja onnx
