name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make RELEASE=1
      run: make RELEASE=1
    - name: Test
      run: make run
