name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu packages
      run: sudo apt install protobuf-c-compiler libprotobuf-c-dev racket
    - name: Initialize submodule
      run: git submodule init
    - name: Update submodule
      run: git submodule update
    - name: make
      run: make
    - name: make run
      run: make run
